language: php
sudo: required
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

install:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev --no-interaction

script:
    - vendor/bin/phpcs --report=full --report-file=./report.txt
    - vendor/bin/phpstan analyse -c phpstan.neon -l max src
    - vendor/bin/atoum -d tests

jobs:
    allow_failures:
        - php: nightly